### ISSUE TITLE
test-init.php: simulating WP init

### ISSUE THREAD

**Issue by ialarmedalien** [ozh/plugin-unit-test-demo#2]
Currently, the shortcode test in test-init.php will pass whether or not you include the line `do_action( 'init' );`. The following set of tests all pass:

``` php
function test_init_plugin() {

    $this->assertTrue( shortcode_exists('omglol') );

    // the following tests are in your original script:
    do_action( 'init' );

    $this->assertEquals( 10, has_action( 'save_post', array( $this->demo_plugin, 'add_meta_if_title' ) ) );
    $this->assertTrue( shortcode_exists('omglol') );
}
```

**Comment by ozh** [comment]
They don't on my setup: see screenshot, if I comment the `do_action`, tests fail. In your example, you're only testing the shortcode array.

![udsfe52](https://cloud.githubusercontent.com/assets/223647/6277538/b9f24f08-b88f-11e4-917a-578d82bdad87.png)

**Comment by ialarmedalien** [comment]
The shortcode test passes both before and after 'init' though -- that is the point. Why does the shortcode exist pre-WP 'init'?

**Comment by ozh** [comment]
Because `add_shortcode()` is immediately available after `shortcodes.php` has been included, and doesn't rely on any hook to be available

**Comment by ialarmedalien** [comment]
Got it -- when you create an instance of the plugin and run the `init` hook, the shortcode is available, and `test-init.php` is run after tests where the plugin gets instantiated.

Thanks for the very useful resource!
